services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
